routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/avaliacao', 'EvaluationController');
Route::resource('/avaliacao/evolucao', 'EvolutionController');

app/Evaluation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Evaluation extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function evolutions()
    {
        return $this->hasMany('App\Evolution')->latest();
    }

    public function scopeFilter($query, Request $request = null)
    {
        $request = $request ?: request();

        if ($request->has('q')) {
            $query->where(function ($query) use ($request) {
                $query->where('name', 'LIKE', "%{$request->q}%")
                    ->orWhere('address', 'LIKE', "%{$request->q}%")
                    ->orWhere('state', 'LIKE', "%{$request->q}%")
                    ->orWhere('city', 'LIKE', "%{$request->q}%")
                    ->orWhere('zipcode', 'LIKE', "%{$request->q}%");
            });
        }

        return $query;
    }
}

app/Http/Controllers/EvaluationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Evaluation;
use App\Evolution;

class EvaluationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function create()
    {
        return view('evaluations.create');
    }

    public function store(Request $request)
    {
        $request->merge(['birthdate' => dbDate($request->birthdate)]);
        $request->merge(['evaluation_date' => dbDate($request->evaluation_date)]);
        $request->merge(['associated_diseases' => arrayToStr($request->associated_diseases)]);
        $request->merge(['family_history' => arrayToStr($request->family_history)]);

        $validator = $this->validation($request);
        if ($validator->fails()) {
            $request->merge(['associated_diseases' => strToArray($request->associated_diseases)]);
            $request->merge(['family_history' => strToArray($request->family_history)]);

            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        if($evaluation = Evaluation::create($request->all())) {
            return redirect()
                ->route('avaliacao.edit', $evaluation->id)
                ->withSuccess('Avaliação criada com sucesso!');
        }

        $request->merge(['associated_diseases' => strToArray($request->associated_diseases)]);
        $request->merge(['family_history' => strToArray($request->family_history)]);

        return back()->withErrors('Erro ao criar a avaliação.')->withinput();
    }

    public function show($id)
    {
        $evaluation = Evaluation::findOrFail($id);
        $evolutions = Evolution::find(request()->get('evolutions'));

        $evaluation->associated_diseases = strToArray($evaluation->associated_diseases);
        $evaluation->family_history = strToArray($evaluation->family_history);

        return view('evaluations.show')->with(compact('evaluation', 'evolutions'));
    }

    public function edit($id)
    {
        $evaluation = Evaluation::findOrFail($id);

        $evaluation->associated_diseases = strToArray($evaluation->associated_diseases);
        $evaluation->family_history = strToArray($evaluation->family_history);

        return view('evaluations.edit')->with(compact('evaluation'));
    }

    public function update($id, Request $request)
    {
        $request->merge(['birthdate' => dbDate($request->birthdate)]);
        $request->merge(['evaluation_date' => dbDate($request->evaluation_date)]);
        $request->merge(['associated_diseases' => arrayToStr($request->associated_diseases)]);
        $request->merge(['family_history' => arrayToStr($request->family_history)]);

        $validator = $this->validation($request);
        if ($validator->fails()) {
            $request->merge(['associated_diseases' => strToArray($request->associated_diseases)]);
            $request->merge(['family_history' => strToArray($request->family_history)]);

            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        $evaluation = Evaluation::findOrFail($id);
        if($evaluation->update($request->all())) {
            return back()->withSuccess('Avaliação atualizada com sucesso!')->with(compact('evaluation'));
        }

        $request->merge(['associated_diseases' => strToArray($request->associated_diseases)]);
        $request->merge(['family_history' => strToArray($request->family_history)]);

        return back()->withErrors('Erro ao atualizar a avaliação.')->withInput();
    }

    public function destroy($id)
    {
        if(Evaluation::destroy($id)) {
            return redirect()->route('home')->withSuccess('Avaliação deletada com sucesso!');
        }

        return back()->withErrors('Erro ao deletar avaliação.');
    }

    protected function validation(Request $request)
    {
        return \Validator::make($request->all(), [
            'birthdate' => 'required|date_format:Y-m-d H:i:s',
            'evaluation_date' => 'required|date_format:Y-m-d H:i:s',
        ]);
    }

}

resources/views/evaluations/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-12 mt-3">
      <form method="POST" action="{{ route('avaliacao.store') }}">
        {{ csrf_field() }}

        <h3 class="mt-3">Dados Pessoais</h3>
        <div class="form-group row">
          <div class="col-md-6">
            <label for="name">Nome</label>
            <input type="text" name="name" class="form-control" id="name" value="{{ old('name') }}" required>
          </div>

          <div class="col-md-2">
            <label for="age">Idade</label>
            <input type="number" name="age" class="form-control" id="age" value="{{ old('age') }}">
          </div>

          <div class="col-md-4">
            <label for="phone">Telefone</label>
            <input type="text" name="phone" class="form-control" id="phone" value="{{ old('phone') }}">
          </div>

          <div class="col-md-2">
            <label for="zipcode">CEP</label>
            <input type="text" name="zipcode" class="form-control" id="zipcode" value="{{ old('zipcode') }}">
          </div>

          <div class="col-md-4">
            <label for="address">Endereço</label>
            <input type="text" name="address" class="form-control" id="address" value="{{ old('address') }}">
          </div>

          <div class="col-md-3">
            <label for="state">Estado</label>
            <input type="text" name="state" class="form-control" id="state" value="{{ old('state') }}">
          </div>

          <div class="col-md-3">
            <label for="city">Cidade</label>
            <input type="text" name="city" class="form-control" id="city" value="{{ old('city') }}">
          </div>

          <div class="col-md-2">
            <label for="gender">Sexo</label>
            <select name="gender" class="form-control" id="gender">
              <option value="m">Masculino</option>
              <option value="f" {{ (old("gender") == 'f' ? "selected":"") }}>Feminino</option>
            </select>
          </div>

          <div class="col-md-2">
            <label for="birthdate">Data de Nascimento</label>
            <input type="text" name="birthdate" class="form-control" id="birthdate" value="{{ brDate(old('birthdate')) }}" required>
          </div>

          <div class="col-md-8">
            <label for="clinical-diagnosis">Diagnóstico Clínico</label>
            <input type="text" name="clinical_diagnosis" class="form-control" id="clinical-diagnosis" value="{{ old('clinical_diagnosis') }}">
          </div>

          <div class="col-md-2">
            <label for="evaluation-date">Data da Avaliação</label>
            <input type="text" name="evaluation_date" class="form-control" id="evaluation-date" value="{{ brDate(old('evaluation_date', date('Y-m-d'))) }}" required>
          </div>

          <div class="col-md-3">
            <label for="responsible">Responsável</label>
            <input type="text" name="responsible" class="form-control" id="responsible" value="{{ old('responsible', 'Dr. Abraão Pontes') }}">
          </div>

          <div class="col-md-3">
            <label for="pa">PA <span class="text-muted">(mmHg)</span></label>
            <input type="text" name="pa" class="form-control" id="pa" value="{{ old('pa') }}">
          </div>

          <div class="col-md-4">
            <label for="fc">FC <span class="text-muted">(bpm)</span></label>
            <input type="text" name="fc" class="form-control" id="fc" value="{{ old('fc') }}">
          </div>
        </div>

        <h3 class="mt-4">Anamnese</h3>
        <div class="form-group row">
          <div class="col-12">
            <label for="qp"><strong>Q.P.</strong></label>
            <textarea rows="1" class="form-control" id="qp" name="qp">{{ old('qp') }}</textarea>
          </div>

          <div class="col-12">
            <label for="hda"><strong>HDA</strong></label>
            <textarea rows="1" class="form-control" id="hda" name="hda">{{ old('hda') }}</textarea>
          </div>

          <div class="col-12">
            <div class="form-check form-check-inline">
              <h6>Doenças associadas</h6>
              <label class="form-check-label ml-0">
                <input class="form-check-input" type="checkbox" name="associated_diseases[]" value="cardiacas" @if(isChecked('cardiacas', old('associated_diseases'))) checked @endif> Cardíacas
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="associated_diseases[]" value="respiratorio" @if(isChecked('respiratorio', old('associated_diseases'))) checked @endif> Respiratório
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="associated_diseases[]" value="neurologicas" @if(isChecked('neurologicas', old('associated_diseases'))) checked @endif> Neurológicas
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="associated_diseases[]" value="metabolicas" @if(isChecked('metabolicas', old('associated_diseases'))) checked @endif> Metabólicas
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="associated_diseases[]" value="dermatologicas" @if(isChecked('dermatologicas', old('associated_diseases'))) checked @endif> Dermatológicas
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="associated_diseases[]" value="visuais" @if(isChecked('visuais', old('associated_diseases'))) checked @endif> Visuais
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="associated_diseases[]" value="endocrinas" @if(isChecked('endocrinas', old('associated_diseases'))) checked @endif> Endôcrinas
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="associated_diseases[]" value="gastrointestinal" @if(isChecked('gastrointestinal', old('associated_diseases'))) checked @endif> Gastrointestinal
              </label>
            </div>
          </div>

          <div class="col-12">
            <label for="associated-diseases-specifications">Especificar</label>
            <textarea rows="1" class="form-control" id="associated-diseases-specifications" name="associated_diseases_specifications">{{ old('associated_diseases_specifications') }}</textarea>
          </div>

          <div class="col-12"><h6>Hábitos de Vida</h6></div>
          <div class="col-12">
            <label for="alimentation">Alimentação</label>
            <textarea rows="1" class="form-control" id="alimentation" name="alimentation">{{ old('alimentation') }}</textarea>
          </div>

          <div class="col-md-6">
            <label for="sleeping">Sono</label>
            <textarea rows="1" class="form-control" id="sleeping" name="sleeping">{{ old('sleeping') }}</textarea>
          </div>

          <div class="col-md-6">
            <label for="sleeping_position">Posição</label>
            <textarea rows="1" class="form-control" id="sleeping_position" name="sleeping_position">{{ old('sleeping_position') }}</textarea>
          </div>

          <div class="col-md-4">
            <div class="form-check form-check-inline">
              <label>Tabagismo</label><br>
              <label class="radio-inline">
                <input type="radio" name="smoking" id="smoking" value="1" @if(old('smoking')) checked @endif> Sim
              </label>
              <label class="radio-inline">
                <input type="radio" name="smoking" id="smoking" value="0" @if(! old('smoking')) checked @endif> Não
              </label>
            </div>
          </div>
          <div class="col-md-8">
            <label for="smoking-frequency">Frequência</label>
            <input type="text" name="smoking_frequency" class="form-control" id="smoking-frequency" value="{{ old('smoking_frequency') }}">
          </div>

          <div class="col-md-4">
            <div class="form-check form-check-inline">
              <label>Etilismo</label><br>
              <label class="radio-inline">
                <input type="radio" name="alcoholism" id="alcoholism" value="1" @if(old('alcoholism')) checked @endif> Sim
              </label>
              <label class="radio-inline">
                <input type="radio" name="alcoholism" id="alcoholism" value="0" @if(! old('alcoholism')) checked @endif> Não
              </label>
            </div>
          </div>
          <div class="col-md-8">
            <label for="alcoholism-frequency">Frequência</label>
            <input type="text" name="alcoholism_frequency" class="form-control" id="alcoholism-frequency" value="{{ old('alcoholism_frequency') }}">
          </div>

          <div class="col-12">
            <div class="form-check form-check-inline">
              <h6>Antecedentes Familiares</h6>
              <label class="form-check-label ml-0">
                <input class="form-check-input" type="checkbox" name="family_history[]" value="diabetes" @if(isChecked('diabetes', old('family_history'))) checked @endif> Diabetes
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="family_history[]" value="hipertensao" @if(isChecked('hipertensao', old('family_history'))) checked @endif> Hipertensão
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="family_history[]" value="cardiopaia" @if(isChecked('cardiopaia', old('family_history'))) checked @endif> Cardiopaia
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="family_history[]" value="neoplasias" @if(isChecked('neoplasias', old('family_history'))) checked @endif> Neoplasias
              </label>
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="family_history[]" value="doenças_hereditarias" @if(isChecked('doenças_hereditarias', old('family_history'))) checked @endif> Doenças Hereditárias
              </label>
            </div>
          </div>
          <div class="col-12">
            <label for="family-history-specifications">Especificar</label>
            <textarea rows="1" class="form-control" id="family-history-specifications" name="family_history_specifications">{{ old('family_history_specifications') }}</textarea>
          </div>

          <div class="col-12">
            <label for="previous-treatments"><strong>Tratamentos Anteriores</strong></label>
            <textarea rows="1" class="form-control" id="previous-treatments" name="previous_treatments">{{ old('previous_treatments') }}</textarea>
          </div>

          <div class="col-12">
            <label for="complementary-exams"><strong>Exames Complementares</strong></label>
            <textarea rows="1" class="form-control" id="complementary-exams" name="complementary_exams">{{ old('complementary_exams') }}</textarea>
          </div>

          <div class="col-12">
            <h3 class="mt-4">Exame Físico</h3>
            <label for="physical-exam"></strong></label>
            <textarea rows="1" class="form-control" id="physical-exam" name="physical_exam">{{ old('physical_exam') }}</textarea>
          </div>

          <div class="col-12 text-center">
            <button type="submit" class="btn btn-primary btn-lg mt-5 px-5">Salvar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/evaluations/show.blade.php
@extends('layouts.app')

@section('content')

<style type="text/css">
   body {
     width: 595px;
     /* to centre page on screen*/
     margin-left: auto;
     margin-right: auto;
     background-color: #fff;
     font-size: 15px;
 }

 header {
  display: none;
 }

 .row div {
  border-bottom: 1px solid black;
  padding: 0;
 }
 .title, .form-check, .no-line {
  border-bottom: 0 !important;
 }
</style>
  <div class="container">
    <div class="row">
      @if(request()->get('evaluation'))
        <div class="col-12 my-2 title"><h5>Dados Pessoais</h5></div>
        <div class="col-12"><strong>Nome:</strong> {{ $evaluation->name }}</div>
        <div class="col-8"><strong>Endereço:</strong> {{ $evaluation->address }}</div>
        <div class="col-4"><strong>Telefone:</strong> {{ $evaluation->phone }}</div>
        <div class="col-6"><strong>Cidade:</strong> {{ $evaluation->city }}</div>
        <div class="col-3"><strong>Estado:</strong> {{ $evaluation->state }}</div>
        <div class="col-3"><strong>CEP:</strong> {{ $evaluation->zipcode }}</div>
        <div class="col-3"><strong>Sexo:</strong> {{ $evaluation->gender == 'm' ? 'Masculino' : 'Feminino' }}</div>
        <div class="col-6"><strong>Data de Nascimento:</strong> {{ brDate($evaluation->birthdate) }}</div>
        <div class="col-3"><strong>Idade:</strong> {{ $evaluation->age }}</div>
        <div class="col-12"><strong>Diagnóstico Clínico:</strong> {{ $evaluation->clinical_diagnosis }}</div>
        <div class="col-5"><strong>Data da Avaliação:</strong> {{ brDate($evaluation->evaluation_date) }}</div>
        <div class="col-7"><strong>Responsável:</strong> {{ $evaluation->responsible }}</div>
        <div class="col-12">
          <strong>Dados vitais:</strong> PA: {{ $evaluation->pa }}mmHg | FC: {{ $evaluation->fc }}bpm
        </div>

        <div class="col-12 my-2 title"><h5>Anamnese</h5></div>
        <div class="col-12"><strong>Q.P.:</strong> {{ $evaluation->qp }}</div>
        <div class="col-12"><strong>HDA:</strong> {{ $evaluation->hda }}</div>
        <div class="col-12 no-line"><strong>Doenças associadas:</strong>
          <div class="form-check form-check-inline ">
            <label class="form-check-label ml-0">
              <input class="form-check-input" type="checkbox" value="cardiacas" @if(isChecked('cardiacas', $evaluation->associated_diseases)) checked @endif> Cardíacas
            </label>
            <label class="form-check-label">
              <input class="form-check-input" type="checkbox"  @if(isChecked('respiratorio', $evaluation->associated_diseases)) checked @endif> Respiratório
            </label>
            <label class="form-check-label">
              <input class="form-check-input" type="checkbox" @if(isChecked('neurologicas', $evaluation->associated_diseases)) checked @endif> Neurológicas
            </label>
            <label class="form-check-label">
              <input class="form-check-input" type="checkbox" @if(isChecked('metabolicas', $evaluation->associated_diseases)) checked @endif> Metabólicas
            </label>
            <label class="form-check-label">
              <input class="form-check-input" type="checkbox" @if(isChecked('dermatologicas', $evaluation->associated_diseases)) checked @endif> Dermatológicas
            </label>
            <label class="form-check-label ml-0">
              <input class="form-check-input " type="checkbox" @if(isChecked('visuais', $evaluation->associated_diseases)) checked @endif> Visuais
            </label>
            <label class="form-check-label">
              <input class="form-check-input" type="checkbox" @if(isChecked('endocrinas', $evaluation->associated_diseases)) checked @endif> Endôcrinas
            </label>
            <label class="form-check-label">
              <input class="form-check-input" type="checkbox"  @if(isChecked('gastrointestinal', $evaluation->associated_diseases)) checked @endif> Gastrointestinal
            </label>
          </div>
        </div>
        <div class="col-12"><strong>Especificar:</strong> {{ $evaluation->associated_diseases_specifications }}</div>
        <div class="col-12 no-line"><strong>Hábitos de Vida</strong></div>
        <div class="col-12"><strong>Alimentação:</strong> {{ $evaluation->alimentation }}</div>
        <div class="col-6"><strong>Sono:</strong> {{ $evaluation->sleeping }}</div>
        <div class="col-6"><strong>Posição:</strong> {{ $evaluation->sleeping_position }}</div>
        <div class="col-3"><strong>Tabagismo:</strong> {{ $evaluation->smoking == 1 ? 'Sim' : 'Não' }}</div>
        <div class="col-9"><strong>Frequência:</strong> {{ $evaluation->smoking_frequency }}</div>
        <div class="col-3"><strong>Etilismo:</strong> {{ $evaluation->alcoholism == 1 ? 'Sim' : 'Não' }}</div>
        <div class="col-9"><strong>Frequência:</strong> {{ $evaluation->alcoholism_frequency }}</div>
        <div class="col-12 no-line">
          <strong>Antecedentes Familiares:</strong>
          <div class="form-check form-check-inline">
            <label class="form-check-label ml-0">
              <input class="form-check-input" type="checkbox" @if(isChecked('diabetes', $evaluation->family_history)) checked @endif> Diabetes
            </label>
            <label class="form-check-label">
              <input class="form-check-input" type="checkbox" @if(isChecked('hipertensao', $evaluation->family_history)) checked @endif> Hipertensão
            </label>
            <label class="form-check-label">
              <input class="form-check-input" type="checkbox" @if(isChecked('cardiopaia', $evaluation->family_history)) checked @endif> Cardiopaia
            </label>
            <label class="form-check-label">
              <input class="form-check-input" type="checkbox" @if(isChecked('neoplasias', $evaluation->family_history)) checked @endif> Neoplasias
            </label>
            <label class="form-check-label">
              <input class="form-check-input" type="checkbox" @if(isChecked('doenças_hereditarias', $evaluation->family_history)) checked @endif> Doenças Hereditárias
            </label>
          </div>
        </div>
        <div class="col-12"><strong>Especificar:</strong> {{ $evaluation->family_history_specifications }}</div>
        <div class="col-12"><strong>Tratamentos Anteriores:</strong> {{ $evaluation->previous_treatments }}</div>
        <div class="col-12"><strong>Exames Complementare:</strong> {{ $evaluation->complementary_exams }}</div>

        <div class="col-12 my-2 title"><h5>Exame Físico</h5></div>
        <div class="col-12">{{ $evaluation->physical_exam }}</div>
      @endif

      @if(count($evolutions))
        <div class="col-12 my-2 title"><h5>Evoluções</h5></div>

        @foreach($evolutions as $evolution)
          <div class="col-12">
            {{ brDate($evolution->evolution_date) }} <br> {{ $evolution->description }}
          </div>
        @endforeach
      @endif
    </div>
  </div>
  <script type="text/javascript">
    javascript:window.print()
  </script>
@endsection