routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/avaliacao', 'EvaluationController');
Route::resource('/avaliacao/evolucao', 'EvolutionController');

app/Evolution.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Evolution extends Model
{
    use SoftDeletes;

    protected $guarded = [];
}

app/Http/Controllers/EvolutionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Evolution;
use App\Evaluation;

class EvolutionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function create()
    {
        $evaluation = Evaluation::findOrFail(request()->get('evaluation'));

        return view('evolutions.create')->with(compact('evaluation'));
    }

    public function store(Request $request)
    {
        $request->merge(['evolution_date' => dbDate($request->evolution_date)]);

        if($evolution = Evolution::create($request->all())) {
            return redirect()->to(route('avaliacao.edit', $request->evaluation_id) . '#ev-' . $evolution->id)
                ->withSuccess('Evolução criada com sucesso!');
        }

        $request->merge(['evolution_date' => brDate($request->evolution_date)]);

        return back()->withErrors('Erro ao criar a evolução.')->withinput();
    }

    public function edit($id)
    {
        $evolution = Evolution::findOrFail($id);
        $evaluation = Evaluation::findOrFail(request()->get('evaluation'));

        return view('evolutions.edit')->with(compact('evolution', 'evaluation'));
    }

    public function update($id, Request $request)
    {
        $request->merge(['evolution_date' => dbDate($request->evolution_date)]);

        if(Evolution::findOrFail($id)->update($request->all())) {
            return redirect()->to(route('avaliacao.edit', $request->evaluation_id) . '#ev-' . $id)
                ->withSuccess('Evolução atualizada com sucesso!');
        }

        return back()->withErrors('Erro ao criar a evolução.')->withinput();
    }

    public function destroy($id)
    {
        if(Evolution::destroy($id)) {
            return redirect()->route('avaliacao.edit', request()->get('evaluation'))
                ->withSuccess('Evolução deletada com sucesso!');
        }

        return back()->withErrors('Erro ao deletar evolução.');
    }
}

resources/views/evolutions/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-12 mt-3">
        <form method="POST" action="{{ route('evolucao.store') }}">
          {{ csrf_field() }}
          <div class="text-muted"><h5>Para: {{ $evaluation->name }}</h5></div>
          <h3 class="mt-3">Evolução</h3>
          <input type="hidden" name="evaluation_id" value="{{ request()->get('evaluation') }}" required>

          <div class="form-group row">
            <div class="col-md-3">
              <label for="evolution-date">Data da evolução</label>
              <input type="text" name="evolution_date" class="form-control" id="evolution-date" value="{{ old('evolution_date', date('d/m/Y')) }}" required>
            </div>

            <div class="col-md-9">
              <label for="description">Descrição</label>
              <textarea rows="1" class="form-control" id="description" name="description" required>{{ old('description') }}</textarea>
            </div>

            <div class="col-12 text-center">
              <button type="submit" class="btn btn-primary btn-lg mt-5 px-5">Salvar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

@endsection

resources/views/evolutions/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-12 mt-3">
        <form method="POST" action="{{ route('evolucao.update', $evolution->id) }}">

          {{ csrf_field() }}
          <input name="_method" type="hidden" value="PUT">

          <div class="text-muted"><h5>Para: {{ $evaluation->name }}</h5></div>
          <h3 class="mt-3">Evolução</h3>
          <input type="hidden" name="evaluation_id" value="{{ request()->get('evaluation') }}" required>

          <div class="form-group row">
            <div class="col-md-3">
              <label for="evolution-date">Data da evolução</label>
              <input type="text" name="evolution_date" class="form-control" id="evolution-date" value="{{ brDate(old('evolution_date', $evolution->evolution_date)) }}" required>
            </div>

            <div class="col-md-9">
              <label for="description">Descrição</label>
              <textarea rows="1" class="form-control" id="description" name="description" required>{{ old('description', $evolution->description) }}</textarea>
            </div>

            <div class="col-12 text-center">
              <button type="submit" class="btn btn-primary btn-lg mt-5 px-5">Salvar</button>
              <a href="#" id="delete" class="btn btn-danger btn-lg mt-5 ml-4 px-5">Deletar</a>
              <a href="{{ route('avaliacao.edit', request()->get('evaluation')) . '#ev-' . $evolution->id }}" class="btn btn-link mt-5 ml-4">Voltar</a>
            </div>
          </div>
        </form>
        <form action="{{ route('evolucao.destroy', [$evolution->id, 'evaluation' => request()->get('evaluation')]) }}" method="POST" id="delete-form" style="display: none">
            <input name="_method" type="hidden" value="DELETE">
            {{ csrf_field() }}
        </form>
      </div>
    </div>
  </div>

@endsection